export const MANAGER_EVENT_TYPES = [
  'requirement.created',
  'requirement.updated',
  'requirement.deleted',
  'requirement.completed',
  'requirements.purged',
  'run.started',
  'run.succeeded',
  'run.failed',
  'run.timed_out',
  'run.cancelled',
  'run.trace.appended',
  'message.created',
  'pull_request.created',
  'pull_request.updated',
  'review_request.started',
  'timer.created',
  'timer.fired',
  'timer.cancelled',
  'manager.reconciled',
  'manager.configuration.updated',
  'agent_models.updated',
] as const;
